[package]

name = "vgmdb-rust"
version = "0.0.1"
authors = ["Bilal Syed Hussain <bilalshussain@gmail.com>"]

[dependencies]
id3 = "*"
rustc-serialize = "0.3"
hyper = "*"
url="*"

[profile.dev]
debug = true   # Controls whether the compiler passes -g or `--cfg ndebug`
